# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: miner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'miner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bminer.proto\x12\x05miner\"\x07\n\x05\x45mpty\"\x19\n\x08IntReply\x12\r\n\x05value\x18\x01 \x01(\x05\"\x19\n\tTxRequest\x12\x0c\n\x04txid\x18\x01 \x01(\x05\"#\n\x0e\x43hallengeReply\x12\x11\n\tchallenge\x18\x01 \x01(\x05\"\x1d\n\x0bStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\x1d\n\x0bWinnerReply\x12\x0e\n\x06winner\x18\x01 \x01(\x05\"C\n\x0cSolutionInfo\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x10\n\x08solution\x18\x02 \x01(\t\x12\x11\n\tchallenge\x18\x03 \x01(\x05\"B\n\rSubmitRequest\x12\x0c\n\x04txid\x18\x01 \x01(\x05\x12\x11\n\tclient_id\x18\x02 \x01(\x05\x12\x10\n\x08solution\x18\x03 \x01(\t\"\x1d\n\x0bSubmitReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\xd7\x02\n\x05Miner\x12\x31\n\x10getTransactionID\x12\x0c.miner.Empty\x1a\x0f.miner.IntReply\x12\x37\n\x0cgetChallenge\x12\x10.miner.TxRequest\x1a\x15.miner.ChallengeReply\x12<\n\x14getTransactionStatus\x12\x10.miner.TxRequest\x1a\x12.miner.StatusReply\x12;\n\x0fsubmitChallenge\x12\x14.miner.SubmitRequest\x1a\x12.miner.SubmitReply\x12\x31\n\tgetWinner\x12\x10.miner.TxRequest\x1a\x12.miner.WinnerReply\x12\x34\n\x0bgetSolution\x12\x10.miner.TxRequest\x1a\x13.miner.SolutionInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'miner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_INTREPLY']._serialized_start=31
  _globals['_INTREPLY']._serialized_end=56
  _globals['_TXREQUEST']._serialized_start=58
  _globals['_TXREQUEST']._serialized_end=83
  _globals['_CHALLENGEREPLY']._serialized_start=85
  _globals['_CHALLENGEREPLY']._serialized_end=120
  _globals['_STATUSREPLY']._serialized_start=122
  _globals['_STATUSREPLY']._serialized_end=151
  _globals['_WINNERREPLY']._serialized_start=153
  _globals['_WINNERREPLY']._serialized_end=182
  _globals['_SOLUTIONINFO']._serialized_start=184
  _globals['_SOLUTIONINFO']._serialized_end=251
  _globals['_SUBMITREQUEST']._serialized_start=253
  _globals['_SUBMITREQUEST']._serialized_end=319
  _globals['_SUBMITREPLY']._serialized_start=321
  _globals['_SUBMITREPLY']._serialized_end=350
  _globals['_MINER']._serialized_start=353
  _globals['_MINER']._serialized_end=696
# @@protoc_insertion_point(module_scope)
